### ISSUE TITLE
It is possible to use PHP 7.4.x with Dolibar 10.0.6+

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#12806]
# Instructions
Hello,

it is possible to use Dolibarr 10.0.6+ with PHP 7.4.x ?

best wishes

# Bug
```
Deprecated: Function get_magic_quotes_gpc() is deprecated in C:\wamp64\www\dolibarr\htdocs\main.inc.php on line 53

Fatal error: Uncaught Error: Class 'mysqli' not found in C:\wamp64\www\dolibarr\htdocs\core\db\mysqli.class.php:205
 Stack trace:
    #0 C:\wamp64\www\dolibarr\htdocs\core\db\mysqli.class.php(91):  DoliDBMysqli->connect('localhost', 'dolibarmysql', 'dolibarr', '', '3307')
    #1 C:\wamp64\www\dolibarr\htdocs\core\lib\functions.lib.php(59): DoliDBMysqli->__construct('mysqli', 'localhost', 'dolibarmysql', 'dolibarr', 'dolibarr', '3307')
    #2 C:\wamp64\www\dolibarr\htdocs\master.inc.php(120): getDoliDBInstance('mysqli', 'localhost', 'dolibarmysql', 'dolibarr', 'dolibarr', '3307')
    #3 C:\wamp64\www\dolibarr\htdocs\main.inc.php(250): require_once('C:\\wamp64\\www\\d...')
    #4 C:\wamp64\www\dolibarr\htdocs\index.php(29): require('C:\\wamp64\\www\\d...')
    #5 {main} thrown in C:\wamp64\www\dolibarr\htdocs\core\db\mysqli.class.php on line 205
```

## Environment
- **Version**: 10.0.6
- **OS**: Windows 10 1909
- **Web server**: Apache 2.7.44.39
- **Database**: MariaDB 10.3.14

## Additional Informations
From 
https://www.php.net/manual/en/migration74.incompatible.php

```
MySQLi

The embedded server functionality has been removed. It was broken since at least PHP 7.0.

The undocumented mysqli::$stat property has been removed in favor of mysqli::stat().
```

**Comment by eldy** [comment]
Dolibarr is compatible with php 7.4 from dolibarr v11 (released soon in january 2020)

**Comment by ghost** [comment]
Thank you :-)
