### ISSUE TITLE
Project object in invoices calculated extrafield causes payments to crash

### ISSUE THREAD

**Issue by suged** [Dolibarr/dolibarr#13606]
11.0.3

I had a calculated extrafield for invoices using a Project object : 
formula (($loadedobj = new Project($db)) && ...

this seemed to cause a PHP crash when accessing payment of some customer invoices
(when I delete this extrafields it works again)
the issue did not apperar in 9.0.2

2020-04-14T12:12:30+02:00 xxx [Tue Apr 14 12:12:30 2020] [error] [client 80.12.67.53] FastCGI: server « /vhost-php-9f64267b-b8e2-4c0d-a435-3905df56b3e4 » stderr: PHP message: PHP Fatal error: Uncaught Error: Class ‹ Project › not found in /volume1/web/dolibarr-cie172/dolibarr-prod/htdocs/core/lib/functions.lib.php(7042) : eval()‹ d code:1, referer: https://xxx/compta/facture/card.php?facid=62&save_lastsearch_values=1
2020-04-14T12:12:30+02:00 xxx [Tue Apr 14 12:12:30 2020] [error] [client 80.12.67.53] FastCGI: server « /vhost-php-9f64267b-b8e2-4c0d-a435-3905df56b3e4 » stderr: Stack trace:, referer: https://xxx/compta/facture/card.php?facid=62&save_lastsearch_values=1
2020-04-14T12:12:30+02:00 xxx [Tue Apr 14 12:12:30 2020] [error] [client 80.12.67.53] FastCGI: server « /vhost-php-9f64267b-b8e2-4c0d-a435-3905df56b3e4 » stderr: #0 /volume1/web/dolibarr-cie172/dolibarr-prod/htdocs/core/lib/functions.lib.php(7042): eval(), referer: https://xxx/compta/facture/card.php?facid=62&save_lastsearch_values=1
2020-04-14T12:12:30+02:00 xxx [Tue Apr 14 12:12:30 2020] [error] [client 80.12.67.53] FastCGI: server « /vhost-php-9f64267b-b8e2-4c0d-a435-3905df56b3e4 » stderr: #1 /volume1/web/dolibarr-cie172/dolibarr-prod/htdocs/core/class/commonobject.class.php(5107): dol_eval( ›(($loadedobj = …’, 1, 0), referer: https://xxx/compta/facture/card.php?facid=62&save_lastsearch_values=1
2020-04-14T12:12:30+02:00 xxx [Tue Apr 14 12:12:30 2020] [error] [client 80.12.67.53] FastCGI: server « /vhost-php-9f64267b-b8e2-4c0d-a435-3905df56b3e4 » stderr: #2 /volume1/web/dolibarr-cie172/dolibarr-prod/htdocs/compta/facture/class/facture.class.php(1588): CommonObject->fetch_optionals(), referer: https://xxx/compta/facture/card.php?facid=62&save_lastsearch_values=1
2020-04-14T12:12:30+02:00 xxx [Tue Apr 14 12:12:30 2020] [error] [client 80.12.67.53] FastCGI: server « /vhost-php-9f64267b-b8e2-4c0d-a435-3905df56b3e4 » stderr: #3 /volume1/web/dolibarr-cie172/dolibarr-prod/htdocs/compta/paiement.php(72): Facture->fetch(‹ 62 ›), referer: https://xxx/compta/facture/card.php?facid=62&save_lastsearch_values=1
2020-04-14T12:12:30+02:00 xxx [Tue Apr 14 12:12:30 2020] [error] [client 80.12.67.53] FastCGI: server « /vhost-php-9f64267b-b8e2-4c0d-a435-3905df56b3e4 » stderr: #4 {main}, referer: https://xxx/compta/facture/card.php?facid=62&save_lastsearch_values=1
2020-04-14T12:12:30+02:00 xxx [Tue Apr 14 12:12:30 2020] [error] [client 80.12.67.53] FastCGI: server « /vhost-php-9f64267b-b8e2-4c0d-a435-3905df56b3e4 » stderr: thrown in /volume1/web/dolibarr-cie172/dolibarr-prod/htdocs/core/lib/functions.lib.php(7042) : eval()'d code on line 1, referer: https://xxx/compta/facture/card.php?facid=62&save_lastsearch_values=1

**Comment by ksar-ksar** [comment]
Hello,

Could you check if it is Ok on newer versions ?

**Comment by ksar-ksar** [comment]
Hello,

I close the issue, if it is still relevant you can re-open it.
