### ISSUE TITLE
Issue with PUT /mos/{id} all time get "Code error 500 : no content"

### ISSUE THREAD

**Issue by hppp69** [Dolibarr/dolibarr#15683]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
I try to use API REST to update manufacturing order with PUT /mos/{id} methode, but all the time I have "Code error 500 : no content"

I try to use updateMosModel like for exemple : 
{
"ref": "LOT-051219-001-1",
"label": "TEST"
}

nothing working

## Environment
- **Version**: 12.0.3
- **OS**: Linux dev-dolibarr-01 5.3.10-1-pve
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: https://dolibarr.xxxxxx.fr/dolibarr/htdocs/api/index.php/mos/5

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments
![error](https://user-images.githubusercontent.com/35064815/101294564-74825080-3818-11eb-8375-0e1bb98c1cd0.png)
) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by hppp69** [comment]
I get more log : 

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mo::update() must be an instance of User, int given, called in /var/www/html/dolibarr/htdocs/mrp/class/api_mos.class.php on line 228 and defined in /var/www/html/dolibarr/htdocs/mrp/class/mo.class.php:573\nStack trace:\n#0 /var/www/html/dolibarr/htdocs/mrp/class/api_mos.class.php(228): Mo->update(5, Object(User))\n#1 [internal function]: Mos->put(5, Array)\n#2 /var/www/html/dolibarr/htdocs/includes/restler/framework/Luracast/Restler/Restler.php(1065): call_user_func_array(Array, Array)\n#3 /var/www/html/dolibarr/htdocs/includes/restler/framework/Luracast/Restler/Restler.php(304): Luracast\\Restler\\Restler->call()\n#4 /var/www/html/dolibarr/htdocs/api/index.php(301): Luracast\\Restler\\Restler->handle()\n#5 {main}\n  thrown in /var/www/html/dolibarr/htdocs/mrp/class/mo.class.php on line 573, referer: https://dolibarr.dev.henpier.fr/dolibarr/htdocs/api/index.php/explorer/`

So is really strange
