### ISSUE TITLE
paiement.php - BILL_PAYED not working

### ISSUE THREAD

**Issue by KARALIFER** [Dolibarr/dolibarr#18181]
At the moment it is no longer possible to enter the payment, the process is canceled and a website with an error is displayed.

![Input](https://user-images.githubusercontent.com/87700547/126310823-3a6d69ad-0a15-4c5e-aa35-8b4c8480e375.JPG)
![Input_2](https://user-images.githubusercontent.com/87700547/126310989-18611189-77e3-40ed-b102-7c3b21f4f10d.JPG)
![Error](https://user-images.githubusercontent.com/87700547/126311078-2e68eba1-47e7-4f83-ac9b-de9c206a4b46.JPG)

---
Log:

2021-07-20 12:28:30 DEBUG   192.168.184.199    No notification to thirdparty sent, nothing into notification setup for the thirdparty socid = 42
2021-07-20 12:28:30 DEBUG   192.168.184.199    dol_getIdFromCode (value for field rowid from key BILL_PAYED not found into cache)
2021-07-20 12:28:30 DEBUG   192.168.184.199    sql=SELECT rowid as valuetoget FROM llx_c_action_trigger WHERE code = 'BILL_PAYED'
2021-07-20 12:28:30 ERR     192.168.184.199    DoliDBMysqli::close Closing a connection with an opened transaction depth=3
2021-07-20 12:28:30 WARNING 192.168.184.199    --- End access to /compta/paiement.php (Warn: db disconnection forced, transaction depth was 3)

**Comment by KARALIFER** [comment]
The same problem occurs as soon as you want to mark the invoice as paid.

![Error_2](https://user-images.githubusercontent.com/87700547/126311760-0e893292-e35b-49a6-9359-2ba7bc9e3d69.JPG)
![Error_2_2](https://user-images.githubusercontent.com/87700547/126311772-aec83953-a796-4922-8511-d00594f2236e.JPG)


URL: compta/facture/card.php?facid=219

LOG:
2021-07-20 12:49:47 DEBUG   192.168.184.199  No notification to thirdparty sent, nothing into notification setup for the thirdparty socid = 42
2021-07-20 12:49:47 DEBUG   192.168.184.199  dol_getIdFromCode (value for field rowid from key BILL_PAYED not found into cache)
2021-07-20 12:49:47 DEBUG   192.168.184.199  sql=SELECT rowid as valuetoget FROM llx_c_action_trigger WHERE code = 'BILL_PAYED'
2021-07-20 12:49:47 ERR     192.168.184.199  DoliDBMysqli::close Closing a connection with an opened transaction depth=1
2021-07-20 12:49:47 WARNING 192.168.184.199  --- End access to /compta/facture/card.php (Warn: db disconnection forced, transaction depth was 1)

**Comment by KARALIFER** [comment]
The problem has existed since version 14

**Comment by ksar-ksar** [comment]
Hello,

Error 500 = PHP error => Have a look on the apache log

**Comment by KARALIFER** [comment]
[20-Jul-2021 15:18:22 Europe/Berlin] PHP Fatal error:  Uncaught Error: Object of class Conf could not be converted to string in D:\inetpub\dolibarr_TEST\htdocs\core\class\notify.class.php:690
Stack trace:
#0 D:\inetpub\dolibarr_TEST\htdocs\core\triggers\interface_50_modNotification_Notification.class.php(97): Notify->send('BILL_PAYED', Object(Facture))
#1 D:\inetpub\dolibarr_TEST\htdocs\core\class\interfaces.class.php(183): InterfaceNotification->runTrigger('BILL_PAYED', Object(Facture), Object(User), Object(Translate), Object(Conf))
#2 D:\inetpub\dolibarr_TEST\htdocs\core\class\commonobject.class.php(5440): Interfaces->run_triggers('BILL_PAYED', Object(Facture), Object(User), Object(Translate), Object(Conf))
#3 D:\inetpub\dolibarr_TEST\htdocs\compta\facture\class\facture.class.php(2418): CommonObject->call_trigger('BILL_PAYED', Object(User))
#4 D:\inetpub\dolibarr_TEST\htdocs\compta\paiement\class\paiement.class.php(393): Facture->setPaid(Object(User), '', '')
#5 D:\inetpub\dolibarr_TEST\htdocs\compta\paiement.php(256): Paiemen in D:\inetpub\dolibarr_TEST\htdocs\core\class\notify.class.php on line 690
[20-Jul-2021 15:18:50 Europe/Berlin] PHP Deprecated:  Directive 'track_errors' is deprecated in Unknown on line 0

**Comment by KARALIFER** [comment]
PHP Fatal error: Uncaught Error: Object of class Conf could not be converted to string in htdocs\core\class\notify.class.php:690

The error did not occur in version 10, 11, 12 and 13. Only since the update to version 14 does the problem persist. 

Dolibarr:
DB Version: 14.0.0

First Setup: 10.0.2

PHP:
Version 7.4.12

OS:
Windows Server 2019

**Comment by ksar-ksar** [comment]
There is a mistake on Line : https://github.com/Dolibarr/dolibarr/blob/a344ae89f22bb6c9a9be0d1699a8623d5207d15b/htdocs/core/class/notify.class.php#L690
						
$dir_output = $$conf->facture->dir_output."/".get_exdir(0, 0, 0, 1, $object, 'invoice');

There is a double $$

**Comment by KARALIFER** [comment]
Yes, it works perfectly after the change. Thanks!
