### ISSUE TITLE
Cannot create supplier invoice from supplier dispatch (reception)

### ISSUE THREAD

**Issue by vmaury** [Dolibarr/dolibarr#20466]
### Bug

**This bug is only visible if PRODUCT_USE_UNITS=true**
If you want to create a supplier invoice from product reception, the received products are note shown, and an exception occurs :
`PHP Fatal error:  Uncaught Error: Call to undefined method CommandeFournisseurDispatch::getLabelOfUnit() in /var/www/html/erp-rec/htdocs/core/class/commonobject.class.php:4436
Stack trace:\n#0 /var/www/html/erp-rec/htdocs/core/class/commonobject.class.php(4315): CommonObject->printOriginLine(Object(CommandeFournisseurDispatch), '', '', '/core/tpl', NULL)
#1 /var/www/html/erp-rec/htdocs/fourn/facture/card.php(2210): CommonObject->printOriginLinesList('', NULL)
#2 {main}\n  thrown in /var/www/html/erp-rec/htdocs/core/class/commonobject.class.php on line 4436, referer: http://172.16.2.3/erp-rec/htdocs/fourn/facture/card.php?action=create&origin=reception&originid=1&socid=51858
`
The temp solution I found is to replace in /htdocs/core/class/commonobject.class.php,
method public function printOriginLine
line ~ 5067 (in master)
```
if (!empty($conf->global->PRODUCT_USE_UNITS)) {
	$this->tpl['unit'] = $langs->transnoentities($line->getLabelOfUnit('long'));
}
```
by
```
if (!empty($conf->global->PRODUCT_USE_UNITS)) {
	if (!method_exists($line, 'getLabelOfUnit')) {
		if (!empty($line->fk_product))	{
			$productstatic->fetch($line->fk_product);
			$this->tpl['unit'] = $langs->transnoentities($productstatic->getLabelOfUnit('long'));
		} else {
			$this->tpl['unit'] ='-';
		}
	} else $this->tpl['unit'] = $langs->transnoentities($line->getLabelOfUnit('long')); // Bug VMA
}
```

### Environment Version

13.0.5 (but I think still buggy in further releases)

### Environment OS

Linux Debian

### Environment Web server

Apache/2.4.25

**Comment by vmaury** [comment]
I guess it's because children lines of class CommandeFournisseurDispatch don't extend CommonObjectLine object, but I don't know to correct thar
