### ISSUE TITLE
Dashboard blank after enabling Services

### ISSUE THREAD

**Issue by JorgeCarousel** [Dolibarr/dolibarr#22052]
### Bug

Hey guys,

I just installed **Dolibarr 15.0.3** on a **Windows** with **Apache 2.4.53**, **PHP 8.1** and **MariaDB 10** on it, I started to enable modules and everything was right until I enabled Services, when I did, the dashboard went blank and Apache logs showed me this:

> [Fri Sep 02 13:12:12.645149 2022] [fcgid:warn] [pid 14496:tid 176] [client 192.168.1.10:22836] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class "Product" not found in D:\\Apache24\\htdocs\\dolibarr\\core\\boxes\\box_services_contracts.php:88, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=624
> [Fri Sep 02 13:12:12.645149 2022] [fcgid:warn] [pid 14496:tid 176] [client 192.168.1.10:22836] mod_fcgid: stderr: Stack trace:, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=624
> [Fri Sep 02 13:12:12.645149 2022] [fcgid:warn] [pid 14496:tid 176] [client 192.168.1.10:22836] mod_fcgid: stderr: #0 D:\\Apache24\\htdocs\\dolibarr\\core\\class\\html.formother.class.php(1334): box_services_contracts->loadBox(), referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=624
> [Fri Sep 02 13:12:12.645149 2022] [fcgid:warn] [pid 14496:tid 176] [client 192.168.1.10:22836] mod_fcgid: stderr: #1 D:\\Apache24\\htdocs\\dolibarr\\index.php(85): FormOther::getBoxesArea(), referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=624
> [Fri Sep 02 13:12:12.645149 2022] [fcgid:warn] [pid 14496:tid 176] [client 192.168.1.10:22836] mod_fcgid: stderr: #2 {main}, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=624
> [Fri Sep 02 13:12:12.645149 2022] [fcgid:warn] [pid 14496:tid 176] [client 192.168.1.10:22836] mod_fcgid: stderr:   thrown in D:\\Apache24\\htdocs\\dolibarr\\core\\boxes\\box_services_contracts.php on line 88, referer: https://dolibarr.example.com/admin/modules.php?mode=commonkanban&page_y=624

Any idea what I can do so I can enable this module?

Thanks.

### Environment Version

15.0.3

### Environment OS

Windows 11 Pro for Workstations

### Environment Web server

Apache 2.4.53 x64

### Environment PHP

8.1

### Environment Database

MariaDB 10

### Expected and actual behavior

Show the dashboard after a new module has been enabled.

### Steps to reproduce the behavior

This is a new install, so install and start enabling modules, after services is enabled, check he dashboard

**Comment by JorgeCarousel** [comment]
Well it turns out I had to enable Products before enabling Services (even when we don't have products, only services) but why didn't services enable it automatically as requirement?
