### ISSUE TITLE
Blank page when trying to generate direct debit SEPA XML file

### ISSUE THREAD

**Issue by hanneshier** [Dolibarr/dolibarr#22875]
### Bug

When I try to generate the direct debit SEPA XML file, I just get a blank white page on the url https://dolibarr.example.org/compta/prelevement/create.php?action=create

I´m using the [tuxgasy Docker image](https://github.com/tuxgasy/docker-dolibarr)

### Environment Version

16.0.1

### Environment OS

Linux 3ac883ff1551 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64

### Environment Web server

Apache/2.4.38 (Debian)

### Environment PHP

8.1.12

### Environment Database

MySQL or MariaDB 10.8.5-MariaDB-1:10.8.5+maria~ubu2204

### Environment URL(s)

/compta/prelevement/create.php

### Expected and actual behavior

Expected to generate and download SEPA XML file
Actually just getting a blank webpage

### Steps to reproduce the behavior

Add some RECUR invoices to direct debit, go the direct debit module and create a RECUR new XML file

### Attached files

Dolibarr logs:
```
dolibarr    | 172.18.0.10 - - [16/Nov/2022:15:28:22 +0000] "GET /compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank HTTP/1.1" 200 8668 "https://verwaltung.innwerk.org/compta/bank/list.php?mainmenu=bank&leftmenu=" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
dolibarr    | 172.18.0.10 - - [16/Nov/2022:15:28:25 +0000] "POST /core/ajax/check_notifications.php HTTP/1.1" 200 395 "https://verwaltung.innwerk.org/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
dolibarr    | [Wed Nov 16 15:28:29.306301 2022] [php:warn] [pid 38] [client 172.18.0.10:37622] PHP Warning:  Undefined variable $socid in /var/www/html/compta/prelevement/create.php on line 364, referer: https://verwaltung.innwerk.org/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
dolibarr    | [Wed Nov 16 15:28:29.307065 2022] [php:warn] [pid 38] [client 172.18.0.10:37622] PHP Warning:  Undefined variable $socid in /var/www/html/compta/prelevement/create.php on line 390, referer: https://verwaltung.innwerk.org/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
dolibarr    | [Wed Nov 16 15:28:29.307080 2022] [php:warn] [pid 38] [client 172.18.0.10:37622] PHP Warning:  Undefined variable $option in /var/www/html/compta/prelevement/create.php on line 393, referer: https://verwaltung.innwerk.org/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank
dolibarr    | 172.18.0.10 - - [16/Nov/2022:15:28:29 +0000] "GET /compta/prelevement/create.php?type= HTTP/1.1" 200 10069 "https://verwaltung.innwerk.org/compta/prelevement/index.php?leftmenu=withdraw&mainmenu=bank" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
dolibarr    | 172.18.0.10 - - [16/Nov/2022:15:28:32 +0000] "POST /core/ajax/check_notifications.php HTTP/1.1" 200 395 "https://verwaltung.innwerk.org/compta/prelevement/create.php?type=" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
dolibarr    | [Wed Nov 16 15:28:33.399027 2022] [php:warn] [pid 39] [client 172.18.0.10:37634] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_CODE_BANQUE in /var/www/html/compta/prelevement/create.php on line 125, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?type=
dolibarr    | [Wed Nov 16 15:28:33.399058 2022] [php:warn] [pid 39] [client 172.18.0.10:37634] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_CODE_GUICHET in /var/www/html/compta/prelevement/create.php on line 125, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?type=
dolibarr    | [Wed Nov 16 15:28:33.408433 2022] [php:warn] [pid 39] [client 172.18.0.10:37634] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 936, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?type=
dolibarr    | [Wed Nov 16 15:28:33.419606 2022] [php:warn] [pid 39] [client 172.18.0.10:37634] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1838, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?type=
dolibarr    | [Wed Nov 16 15:28:33.419864 2022] [php:warn] [pid 39] [client 172.18.0.10:37634] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1874, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?type=
dolibarr    | [Wed Nov 16 15:28:33.419914 2022] [php:warn] [pid 39] [client 172.18.0.10:37634] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1838, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?type=
dolibarr    | [Wed Nov 16 15:28:33.419950 2022] [php:warn] [pid 39] [client 172.18.0.10:37634] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1874, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?type=
dolibarr    | [Wed Nov 16 15:28:33.421210 2022] [php:error] [pid 39] [client 172.18.0.10:37634] PHP Fatal error:  Uncaught TypeError: chmod(): Argument #1 ($filename) must be of type string, resource given in /var/www/html/compta/prelevement/class/bonprelevement.class.php:1693\nStack trace:\n#0 /var/www/html/compta/prelevement/class/bonprelevement.class.php(1693): chmod()\n#1 /var/www/html/compta/prelevement/class/bonprelevement.class.php(1067): BonPrelevement->generate()\n#2 /var/www/html/compta/prelevement/create.php(125): BonPrelevement->create()\n#3 {main}\n  thrown in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1693, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?type=
dolibarr    | 172.18.0.10 - - [16/Nov/2022:15:28:33 +0000] "POST /compta/prelevement/create.php?action=create HTTP/1.1" 500 321 "https://verwaltung.innwerk.org/compta/prelevement/create.php?type=" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
d
```

**Comment by ksar-ksar** [comment]
Hello,

Should be fixed on V16.0.2 : https://github.com/Dolibarr/dolibarr/commit/bea16a5256c66584259639eebf1c20891fef0780

**Comment by hanneshier** [comment]
Thank you, will check es soon as tuxagasy/docker-dolibarr is updated to 16.0.2

**Comment by hanneshier** [comment]
Unfortunately, the problem still exists in 16.0.3

```
dolibarr    | 172.18.0.10 - - [01/Dec/2022:23:35:34 +0000] "POST /core/ajax/check_notifications.php HTTP/1.1" 200 395 "https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0"
dolibarr    | [Thu Dec 01 23:35:41.809074 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_CODE_BANQUE in /var/www/html/compta/prelevement/create.php on line 125, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.809142 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_CODE_GUICHET in /var/www/html/compta/prelevement/create.php on line 125, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.825193 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 937, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.839479 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1839, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.839560 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1875, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.839592 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1839, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.839617 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1875, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.839641 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_END_TO_END in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1839, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.839676 2022] [php:warn] [pid 36] [client 172.18.0.10:59324] PHP Warning:  Undefined property: stdClass::$PRELEVEMENT_USTRD in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1875, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
dolibarr    | [Thu Dec 01 23:35:41.840610 2022] [php:error] [pid 36] [client 172.18.0.10:59324] PHP Fatal error:  Uncaught TypeError: chmod(): Argument #1 ($filename) must be of type string, resource given in /var/www/html/compta/prelevement/class/bonprelevement.class.php:1694\nStack trace:\n#0 /var/www/html/compta/prelevement/class/bonprelevement.class.php(1694): chmod()\n#1 /var/www/html/compta/prelevement/class/bonprelevement.class.php(1068): BonPrelevement->generate()\n#2 /var/www/html/compta/prelevement/create.php(125): BonPrelevement->create()\n#3 {main}\n  thrown in /var/www/html/compta/prelevement/class/bonprelevement.class.php on line 1694, referer: https://verwaltung.innwerk.org/compta/prelevement/create.php?mainmenu=bank
```

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?

**Comment by Adventurousdonut** [comment]
I have the same problem in version 19.0.0. I'm also using tuxgasy's Docker image.
When trying to create payment order by direct debit it just links to a blank page with the URL: https://dolibarr.example/compta/prelevement/create.php?type=
