### ISSUE TITLE
Can't add items to invoice unter PHP8.0 and 8.1

### ISSUE THREAD

**Issue by will2877** [Dolibarr/dolibarr#23339]
### Bug

I setup a new instance of Dolibarr 16.0 and tried to create an invoice. 
The part to add positions doesn't appear for some reason. 
If I switch to PHP7.4 it works fine.

I had the same issue on a long running Dolibarr 14.0.5.

### Environment Version

16.0.3 & 14.0.5

### Environment OS

freeBSD

### Environment Web server

Apache

### Environment PHP

8.0 & 8.1

### Environment Database

MariaDB

**Comment by milenmk** [comment]
V16 doesn't support fully PHP8. Try with PHP 7.4 OR look at your Dolibarr log and post the error here.

**Comment by ksar-ksar** [comment]
Hello,

Could you send us the error.log from Apache ?

**Comment by will2877** [comment]
stderr: PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in /core/class/translate.class.php:641
stderr: Stack trace:
stderr: #0 /home/z/www/x/erp/public/core/class/translate.class.php(641): sprintf('%', '', '', '', '')
stderr: #1 /home/z/www/x/erp/public/core/tpl/objectline_create.tpl.php(136): Translate->trans('ReductionShort')
stderr: #2 /home/z/www/x/erp/public/core/class/commonobject.class.php(4837): include('/home/awegeduz/...')
stderr: #3 /home/z/www/x/erp/public/compta/facture/card.php(5365): CommonObject->formAddObjectLine(1, Object(Societe), Object(Societe))
stderr: #4 {main}
stderr:   thrown in /home/z/www/x/erp/public/core/class/translate.class.php on line 641

**Comment by nydeggerm** [comment]
Same here. I'm Swiss German and found the source of the problem: "ReductionShort" and "ReductionsShort" ist not translated and contains an "%"
I guess this happens also in other languages. I haven't checked them.

Swiss German: "ReductionShort" and "ReductionsShort" must be "Rabatt"
https://github.com/Dolibarr/dolibarr/blob/e76641c491e4105e9cb1ded6149771c621d822b5/htdocs/langs/de_CH/bills.lang#L122
https://github.com/Dolibarr/dolibarr/blob/e76641c491e4105e9cb1ded6149771c621d822b5/htdocs/langs/de_CH/bills.lang#L124

German:
https://github.com/Dolibarr/dolibarr/blob/e76641c491e4105e9cb1ded6149771c621d822b5/htdocs/langs/de_DE/bills.lang#L306
https://github.com/Dolibarr/dolibarr/blob/e76641c491e4105e9cb1ded6149771c621d822b5/htdocs/langs/de_DE/bills.lang#L308




Workaround:
I've changed the two strings it manually in my Dolibarr installation via web GUI on the page /admin/translation.php and the error disappeared.

**Comment by emheyarssi** [comment]
This should be fixed in Transifex, not directly in source code.
Is ok as a quick fix but a next update the file will be overwrited.

**Comment by n15c** [comment]
Had the same issue under Dolibarr 17.0.3 after switching to PHP 8.x

**Comment by sarusani** [comment]
The problem is not that the string is not translated correctly. The current translation "%" (Prozent) is a perfectly valid short translation of the word Rabatt.

The problem is that Dolibarr can't handle a string when it contains a single %. This should not be fixed in Transifex, it should be handled correctly in translate.class.php.

(In PHP7 sprintf() returned false when a error occured. In PHP8 it returns a ValueError. Hence the different behavior.)
