### ISSUE TITLE
V17.0.0 Setup of invoices fails when lang=nb_NO

### ISSUE THREAD

**Issue by terhoy** [Dolibarr/dolibarr#24193]
### Bug

Hi,

Thanks for the great work with Dolibarr, highly appreciated!

Installed a fresh version 17 of Dolibarr.  When language is set to nb_NO the setup of the invoice module partly fails. Look at enclosed screen dump "Invoice setup lang=en_GB.JPG" and "Invoice setup lang=nb_NO.JPG"

The Dolibarr error_log states: 

[12-Mar-2023 11:50:05 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: 11 arguments are required, 5 given in /home/krogevhn/public_html/dolibarr/core/class/translate.class.php:641
Stack trace:
#0 /home/krogevhn/public_html/dolibarr/core/class/translate.class.php(641): sprintf()
#1 /home/krogevhn/public_html/dolibarr/core/modules/facture/mod_facture_mars.php(81): Translate->trans()
#2 /home/krogevhn/public_html/dolibarr/admin/facture.php(345): mod_facture_mars->info()
#3 {main}
  thrown in /home/krogevhn/public_html/dolibarr/core/class/translate.class.php on line 641

![Invoice setup lang=en_GB](https://user-images.githubusercontent.com/70033666/224542633-6df6054f-49b9-4144-977a-af1f4e762a63.JPG)
![Invoice setup lang=nb_NO](https://user-images.githubusercontent.com/70033666/224542639-0c6b899a-1ad6-40e5-81fd-51b9ecbbcaeb.JPG)

[error_log.txt](https://github.com/Dolibarr/dolibarr/files/10950684/error_log.txt)

### Environment Version

17

### Environment OS

Linux x86_64 	3.10.0-962.3.2.lve1.5.42.el6h.x86_64

### Environment Web server

Apache 2.4.55

### Environment PHP

8.1

### Environment Database

MySQL 5.7.40-cll-lve

### Environment URL(s)

/dolibarr/admin/facture.php?save_lastsearch_values=1&backtopage=%2Fdolibarr%2Fadmin%2Fmodules.php

### Expected and actual behavior

Setup page for module Invoice is only partly shown. When lang=nb_N= the "Invoices and credit notes numbering model" only show the name "Mars". When lang=en_GB the whole page is shown.

![Invoice setup lang=nb_NO](https://user-images.githubusercontent.com/70033666/224542068-3349a5af-0abd-4dd7-829d-6c765e2716b6.JPG)
![Invoice setup lang=en_GB](https://user-images.githubusercontent.com/70033666/224542069-dd58d848-9ccb-4684-bb4f-84ab33f33470.JPG)

### Steps to reproduce the behavior

Change Default language to "nb_NO". Go to "Moduler/Applikasjoner" and choose "Fakturaer". Click on the cogwheel to setup the module.

![default language=nb_NO](https://user-images.githubusercontent.com/70033666/224542170-f0db0ab3-09ef-46dd-b7c3-2e63da0b244e.JPG)
![Fakturaoppsett](https://user-images.githubusercontent.com/70033666/224542554-a226f80d-4f19-4aea-912b-80c1a5aba1bc.JPG)

### Attached files

Please find enclosed the error_log.txt and dolibarr.log
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/10950698/dolibarr.log)
[error_log.txt](https://github.com/Dolibarr/dolibarr/files/10950699/error_log.txt)

**Comment by frederic34** [comment]
with php 7.4 
![image](https://user-images.githubusercontent.com/3624836/225013569-bee7ed2a-f750-416e-bd72-190b3af034e0.png)

with 8.1 : 

![image](https://user-images.githubusercontent.com/3624836/225010660-ef1db913-87bc-4dd1-941a-533d107c8684.png)

**Comment by terhoy** [comment]
> with php 7.4 ![image](https://user-images.githubusercontent.com/3624836/225013569-bee7ed2a-f750-416e-bd72-190b3af034e0.png)
> 
> with 8.1 :
> 
> ![image](https://user-images.githubusercontent.com/3624836/225010660-ef1db913-87bc-4dd1-941a-533d107c8684.png)

Thanks frederic34, confirming that changing to php version 7.4 solved this problem.

Regards

**Comment by Hystepik** [comment]
Hello,
I think it's fixed, can you check with the last version of 17.0.3

**Comment by terhoy** [comment]
Thank's @Hystepik I've upgraded to version 19. This case can be closed.

**Comment by terhoy** [comment]
Thank's @Hystepik I've upgraded to version 19. This case can be closed.
