### ISSUE TITLE
Entering supplier payments not possible anymore

### ISSUE THREAD

**Issue by mschiessl** [Dolibarr/dolibarr#25752]
### Bug

I've just successfully entered a supplier payment and when hovering to the next payment, i am not seeing the full screen any longer. 
The screen looks like this:
![image](https://github.com/Dolibarr/dolibarr/assets/5146717/61d66949-0f66-4112-95fb-236cd5f10312)

PHP 8.1 (also tried with php8.2) Logs say the following 
```
2023/08/31 12:55:10 [error] 3931785#3931785: *685396 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "labeladddateof" in /var/www/dolibarr.mysrv/chroot/htdocs/core/class/html.form.class.php on line 7076; PHP message: PHP Fatal error:  Uncaught TypeError: DateTime::setTimestamp(): Argument #1 ($timestamp) must be of type int, string given in /var/www/dolibarr.mysrv/chroot/htdocs/core/lib/functions.lib.php:2930
Stack trace:
#0 /var/www/dolibarr.mysrv/chroot/htdocs/core/lib/functions.lib.php(2930): DateTime->setTimestamp()
#1 /var/www/dolibarr.mysrv/chroot/htdocs/core/class/html.form.class.php(7077): dol_getdate()
#2 /var/www/dolibarr.mysrv/chroot/htdocs/fourn/facture/paiement.php(512): Form->selectDate()
#3 {main}
  thrown in /var/www/dolibarr.mysrv/chroot/htdocs/core/lib/functions.lib.php on line 2930" while reading upstream, client: <someIP>, server: dolibarr.mysrv, request: "GET /fourn/facture/paiement.php?facid=423&action=create&page_y=36 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/fpm-dolibarr.mysrv.sock:", host: "dolibarr.mysrv", referrer: "https://dolibarr.mysrv/fourn/facture/card.php?facid=423&save_lastsearch_values=1"
2023/08/31 12:55:10 [error] 3931785#3931785: *685398 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: array_sum(): Argument #1 ($array) must be of type array, string given in /var/www/dolibarr.mysrv/chroot/htdocs/compta/ajaxpayment.php:84
Stack trace:
#0 /var/www/dolibarr.mysrv/chroot/htdocs/compta/ajaxpayment.php(84): array_sum()
#1 {main}
  thrown in /var/www/dolibarr.mysrv/chroot/htdocs/compta/ajaxpayment.php on line 84" while reading response header from upstream, client: 2003:e7:6711:4400:7804:e1dd:c47d:e213, server: dolibarr.mysrv, request: "POST /compta/ajaxpayment.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/fpm-dolibarr.mysrv.sock:", host: "dolibarr.mysrv", referrer: "https://dolibarr.mysrv/fourn/facture/paiement.php?facid=423&action=create&page_y=36"
```

### Environment Version

18.0.0

### Environment OS

Debian GNU/Linux 11

### Environment Web server

nginx

### Environment PHP

PHP 8.1.22

### Environment Database

Ver 15.1 Distrib 10.6.15-MariaDB

### Expected and actual behavior

Being able to see the full "payments" screen.

The current behaviour happens in all available browser (Chrome, Safari, FireFox) and as well in anonymous mode.

### Steps to reproduce the behavior

I have no clue what changed, as it was working with all the given versions beforehand.
After entering a payment, it stopped working randomly

**Comment by mschiessl** [comment]
Lowering PHP to PHP7.4 fixes this issue

**Comment by Hystepik** [comment]
18.0.1 is suppose to accept php 8.1. I reopen to fix
