### ISSUE TITLE
Admin login error after upgrade to 18.0.1

### ISSUE THREAD

**Issue by ccolussi** [Dolibarr/dolibarr#25975]
### Bug

Admin login error (admin is a internal user), normal users (ldap) login ok.

### Environment Version

18.0.1

### Environment OS

Centos 8

### Environment Web server

Apache 2

### Environment PHP

8.2.10

### Environment Database

PostgreSQL

### Expected and actual behavior

Login ok

### Steps to reproduce the behavior

Login with admin user, admin user not use ldap to login.

### Attached files

[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1286
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1286
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1286
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1287
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1287
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1287
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1288
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1288
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1288
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1289
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1289
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1289
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1290
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1290
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1290
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1291
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1291
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1291
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1292
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1292
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1292
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1294
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1294
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1294
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1303
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1303
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1303
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Undefined array key 0 in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1312
[19-Sep-2023 19:24:57 UTC] PHP Warning:  Trying to access array offset on value of type null in /var/www/xyz_com_br/dolibarr/htdocs/core/class/ldap.class.php on line 1312
[19-Sep-2023 19:24:57 UTC] PHP Fatal error:  Uncaught Error: LDAP connection has already been closed in /var/www/xyz_com_br/dolibarr/htdocs/core/login/functions_ldap.php:268
Stack trace:
#0 /var/www/xyz_com_br/dolibarr/htdocs/core/login/functions_ldap.php(268): ldap_errno()
#1 /var/www/xyz_com_br/dolibarr/htdocs/core/lib/security2.lib.php(98): check_user_password_ldap()
#2 /var/www/xyz_com_br/dolibarr/htdocs/main.inc.php(821): checkLoginPassEntity()
#3 /var/www/xyz_com_br/dolibarr/htdocs/index.php(31): require('...')
#4 {main}
  thrown in /var/www/xyz_com_br/dolibarr/htdocs/core/login/functions_ldap.php on line 268

**Comment by glu000** [comment]
any updates on this issue?

**Comment by W1W1-M** [comment]
Hello,
In order to analyse the problem, can you provide the LDAP conf from your Dolibarr `conf.php` ?

**Comment by captain-nut** [comment]
I encountered the same issue after upgrading from Debian 11 to Debian 12 (moving from PHP 7.4 to PHP 8.2) while using Dolibarr 19.03.

When attempting to log in with a local user, I received an HTTP 500 error. Checking the Apache logs revealed the following error:

PHP Fatal error:  Uncaught Error: LDAP connection has already been closed in /usr/share/dolibarr/htdocs/core/login/functions_ldap.php:249\n
Stack trace:\n
#0 /usr/share/dolibarr/htdocs/core/login/functions_ldap.php(249): ldap_errno()\n
#1 /usr/share/dolibarr/htdocs/core/lib/security2.lib.php(98): check_user_password_ldap()\n
#2 /usr/share/dolibarr/htdocs/main.inc.php(863): checkLoginPassEntity()\n
#3 /usr/share/dolibarr/htdocs/index.php(31): require('...')\n#4 {main}\n
  thrown in /usr/share/dolibarr/htdocs/core/login/functions_ldap.php on line 249, referer: https://<<domain-url>>/

As a temporary workaround, I changed the order of the authentication backends in the Dolibarr configuration file from:
$dolibarr_main_authentication='ldap,dolibarr';
to:
$dolibarr_main_authentication='dolibarr,ldap';

This allowed me to successfully log in with correct local or LDAP credentials. 
However, if the credentials are incorrect, I still receive an HTTP 500 error instead of the usual login error message with the same error in the logs


ldap section of the conf file

// Authentication settings
//$dolibarr_main_authentication='dolibarr';
$dolibarr_main_authentication='dolibarr,ldap';   // To be able to login with both the LDAP or the Dolibarr password (if there is problem with the LDAP server, keep a non LDAP password for one >

$dolibarr_main_auth_ldap_host='192.168.10.253';  //<hostname>';  // Plusieurs serveurs peuvent être ajouter en séparant par une virgule.
$dolibarr_main_auth_ldap_port='389';    // Port
$dolibarr_main_auth_ldap_version='3';
$dolibarr_main_auth_ldap_servertype='activedirectory';  // openldap, activedirectory or egroupware
$dolibarr_main_auth_ldap_login_attribute='samaccountname';  // Ex: uid or samaccountname for active directory
$dolibarr_main_auth_ldap_dn='dc=ad,dc=integra-tek,dc=com'; // Ex: ou=users,dc=my-domain,dc=com
//$dolibarr_main_auth_ldap_filter = '';            // If defined, two previous parameters are not used to find a user into LDAP. Ex: (uid=%1%) or &(uid=%1%)(isMemberOf=$
$dolibarr_main_auth_ldap_admin_login='cn=Administrator,cn=Users,dc=ad,dc=integra-tek,dc=com';     // Required only if anonymous bind disabled. Ex: cn=admin,dc=example,dc=com
$dolibarr_main_auth_ldap_admin_pass='********';            // Required only if anonymous bind disabled. Ex: secret
$dolibarr_main_auth_ldap_debug='false';

**Comment by W1W1-M** [comment]
LDAP fixes for this will be in next v19 maintenance release

**Comment by strk** [comment]
is this to be closed ?
