### ISSUE TITLE
Missing modules in the modules config section

### ISSUE THREAD

**Issue by gherasasmaa** [Dolibarr/dolibarr#27241]
### Bug

**The end of the page is missing**

![image](https://github.com/Dolibarr/dolibarr/assets/62083497/c808cd04-97e4-43cc-9750-956bb91509be)

And this is the bug reported by PHP

: Uncaught Error: Call to undefined function mb_strlen() in /var/www/dolibarr/htdocs/includes/parsedown/Parsedown.php:170 
Stack trace: #0 /var/www/dolibarr/htdocs/includes/parsedown/Parsedown.php(39): Parsedown->lines() #1 /var/www/dolibarr/htdocs/core/lib/parsemd.lib.php(53): Parsedown->text() #2 /var/www/dolibarr/htdocs/core/modules/DolibarrModules.class.php(702): dolMd2Html() #3 /var/www/dolibarr/htdocs/admin/modules.php(704): DolibarrModules->getDescLong() #4 {main} thrown in**/var/www/dolibarr/htdocs/includes/parsedown/Parsedown.php** on line170

**I resolved it by installing the PHP extension**
sudo apt-get install php-mbstring
sudo service apache2 restart

And here is the environment : Dolibarr 18.0.3, PHP 8.2.7, Serveur sous Debian 6.1.66-1

### Environment Version

18.0.3

### Environment OS

Debian 6.1.66-1

### Environment Web server

Apache/2.4.57

### Environment PHP

8.2.7

### Environment URL(s)

htdocs/admin/modules.php?mainmenu=home

**Comment by altairis-tof** [comment]
Hello @gherasasmaa 
According to the wiki Dolibarr the mbstring php extension if database is not utf8.
Can you confirm it's your case please ?
https://wiki.dolibarr.org/index.php?title=Dependencies_and_external_libraries
