### ISSUE TITLE
Can not attach a file to a proposal/invoice

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#27818]
### Bug

I get "Le champ 'Fichier' est obligatoire" when I try to attach a file to a proposal.

### Environment Version

18.0.2

### Environment OS

debian

### Environment URL(s)

olibarr/compta/facture/document.php

### Expected and actual behavior

File should be uploaded or error message should be clearer.

### Steps to reproduce the behavior

Create a proposal or invoice.  (My proposal is open, my invoice was already validated).
The invoice upload should work.

It worked before, but I applied the recommended security settings, so it may be related to that.
I can generate PDFs which are attached to the objects, the dolibarrdocs directory is writable...

The error message does not seem to be a good description of what is happening, finding the reason is likely easier.

Any suggestion what to look for/where to look?

I found the translation string in "cron.lang", maybe it's related to cron.

```
htdocs/langs/fr_FR/cron.lang:CronFieldMandatory=Le champ %s est obligatoire
```

I did also fix the confiruation of a cron task recently.  It's strange that this would impact the file upload.

**Comment by mdeweerd** [comment]
I found this in my access.log:

```plaintext
PHP Warning:  File upload error - unable to create a temporary file in Unknown on line 0, referer: https://SERVER/dolibarr/compta/facture/document.php?id=415&uploadform=1
```

And after throwing an exception in 'function trans()' when param1 is 'Fichier', I found the following stacktrace.
```plaintext
[php:error] [pid 256847] [client 192.168.0.254:39250] PHP Fatal error:  Uncaught Exception: HeRE in /home/www/SERVER/dolibarr18/htdocs/core/class/translate.class.php:633
Stack trace:
#0 /home/www/SERVER/dolibarr18/htdocs/core/actions_linkedfiles.inc.php(65): Translate->trans()
#1 /home/www/SERVER/dolibarr18/htdocs/compta/facture/document.php(91): include('...')
#2 {main}
  thrown in /home/www/SERVER/dolibarr18/htdocs/core/class/translate.class.php on line 633, referer: https://SERVER/dolibarr/compta/facture/document.php?id=415&uploadform=1
```

Implying that this line is not generating the the best user oriented message for the case where the temporary file can not be created:
```php
                                        setEventMessages($langs->trans("ErrorFieldRequired", $langs->transnoentitiesnoconv("File")), null, 'errors');
```

And probably related to adjusting the open_basedir path.

**Comment by mdeweerd** [comment]
Solved, access to the /tmp directory was also required and not included in the open_basedir specification.
