### ISSUE TITLE
DebugBar Fatal error: Uncaught Error: Class 'Psr\Log\AbstractLogger'

### ISSUE THREAD

**Issue by Daviid-P** [Dolibarr/dolibarr#28333]
### Bug

I'm testing Jenkins for autodeployment and after deplyment I get this error:
```
Fatal error: Uncaught Error: Class 'Psr\Log\AbstractLogger' not found in /share/ZFS2_DATA/Web/dolibarr/htdocs/includes/maximebf/debugbar/src/DebugBar/DataCollector/MessagesCollector.php:20 Stack trace: #0 /share/ZFS2_DATA/Web/dolibarr/htdocs/debugbar/class/autoloader.php(12): require_once() #1 [internal function]: {closure}('DebugBar\\DataCo...') #2 /share/ZFS2_DATA/Web/dolibarr/htdocs/debugbar/class/DataCollector/DolMessagesCollector.php(9): spl_autoload_call('DebugBar\\DataCo...') #3 /share/ZFS2_DATA/Web/dolibarr/htdocs/core/lib/functions.lib.php(1194): include_once('/share/ZFS2_DAT...') #4 /share/ZFS2_DATA/Web/dolibarr/htdocs/debugbar/class/DebugBar.php(8): dol_include_once('/debugbar/class...') #5 /share/ZFS2_DATA/Web/dolibarr/htdocs/main.inc.php(381): include_once('/share/ZFS2_DAT...') #6 /share/ZFS2_DATA/Web/dolibarr/htdocs/admin/modules.php(36): require('/share/ZFS2_DAT...') #7 {main} in /share/ZFS2_DATA/Web/dolibarr/htdocs/includes/maximebf/debugbar/src/DebugBar/DataCollector/MessagesCollector.php on line 20
```

I've checked with winmerge and all the files listed are identical in testing and production.

Both environments run on the same QNAP NAS, same Apache and same PHP, simply 2 different folders.

As suggested here, https://github.com/Dolibarr/dolibarr/issues/15914, disabling DebugBar allows me to use Dolibarr again, but I have no idea why this error happens.

I've tried to install xdebug and see if I can step-by-step find the problem but QNAP sucks and I can't get xdebug to work.

**Comment by Daviid-P** [comment]
I ended up having this same problem again and couldn't remember how I fixed it.

So in case I end up here again in the future here's what I just did to fix it:

`sudo mv /var/www/html/Dolibarr/htdocs/includes/psr /var/www/html/Dolibarr/htdocs/includes/Psr`

`htdocs\debugbar\class\autoloader.php`

```php
	if (preg_match('/^'.preg_quote('Psr\Log', '/').'/', $class)) {
		$file = DOL_DOCUMENT_ROOT.'/includes/'.str_replace('\\', DIRECTORY_SEPARATOR, $class).'.php';
		//var_dump($class.' - '.file_exists($file).' - '.$file);
		if (file_exists($file)) {
			require_once $file;
			return true;
		}
		return false;
	}
```


This always worked on Windows because it doesn't care about case on path.


Do let me know if I'm wrong but doing the `mv` fixed it for me on `Linux EVIVA-DevLT 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`


The error was not the `Psr\Log\AbstractLogger` specifically, it was just the first one to be loaded.
