### ISSUE TITLE
Error when importing an excel to fill product stocks

### ISSUE THREAD

**Issue by alihusseinc** [Dolibarr/dolibarr#29106]
### Bug

When I try to import an Excel to fill product stocks, I get a 500 error page

![s](https://github.com/Dolibarr/dolibarr/assets/104669840/8d3c47e1-96f7-4889-9fdc-8fa3cff39976)

![sx](https://github.com/Dolibarr/dolibarr/assets/104669840/0b5426bc-b0ae-4996-9591-5ad6fb03b89e)

**Comment by JonBendtsen** [comment]
which version of dolibarr? What kind of setup do you have? PHP version, database version, ...

What does the dolibarr.log file contain?

**Comment by alihusseinc** [comment]
dolibarr 19.0.1,php 8.2.12, phpMyAdmin 5.2.1, xampp
[dolibarr.log](https://github.com/Dolibarr/dolibarr/files/14792725/dolibarr.log)

**Comment by JonBendtsen** [comment]
okay, and your webservers log file? what does that say?

**Comment by alihusseinc** [comment]
[Thu Mar 28 13:19:38.538505 2024] [php:warn] [pid 3156:tid 1900] [client ::1:59511] PHP Warning:  file_get_contents(): Unable to find the wrapper &quot;zip&quot; - did you forget to enable it when you configured PHP? in C:\\xampp\\htdocs\\dolibarr\\includes\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Reader\\Security\\XmlScanner.php on line 152, referer: http://localhost/
[Thu Mar 28 13:19:38.541540 2024] [php:warn] [pid 3156:tid 1900] [client ::1:59511] PHP Warning:  file_get_contents(zip://C:\\xampp\\htdocs\\dolibarr\\documents\\import\\temp\\20240328171935-teste.xlsx#xl/worksheets/sheet1.xml): Failed to open stream: No such file or directory in C:\\xampp\\htdocs\\dolibarr\\includes\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Reader\\Security\\XmlScanner.php on line 152, referer: http://localhost/
[Thu Mar 28 13:19:38.542541 2024] [php:error] [pid 3156:tid 1900] [client ::1:59511] PHP Fatal error:  Uncaught ValueError: XMLReader::XML(): Argument #1 ($source) cannot be empty in C:\\xampp\\htdocs\\dolibarr\\includes\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Reader\\Xlsx.php:206\nStack trace:\n#0 C:\\xampp\\htdocs\\dolibarr\\includes\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Reader\\Xlsx.php(206): XMLReader->XML('', NULL, 12)\n#1 C:\\xampp\\htdocs\\dolibarr\\core\\modules\\import\\import_xlsx.modules.php(310): PhpOffice\\PhpSpreadsheet\\Reader\\Xlsx->listWorksheetInfo('C:/xampp/htdocs...')\n#2 C:\\xampp\\htdocs\\dolibarr\\imports\\import.php(836): ImportXlsx->import_read_record()\n#3 {main}\n  thrown in C:\\xampp\\htdocs\\dolibarr\\includes\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Reader\\Xlsx.php on line 206, referer: http://localhost/

**Comment by JonBendtsen** [comment]
> [Thu Mar 28 13:19:38.538505 2024] [php:warn] [pid 3156:tid 1900] [client ::1:59511] PHP Warning: file_get_contents(): Unable to find the wrapper "zip" - did you forget to enable it when you configured PHP? in C:\xampp\htdocs\dolibarr\includes\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Security\XmlScanner.php on line 152, referer: http://localhost/ 

Are php-zip package installed?

> [Thu Mar 28 13:19:38.541540 2024] [php:warn] [pid 3156:tid 1900] [client ::1:59511] PHP Warning: file_get_contents(zip://C:\xampp\htdocs\dolibarr\documents\import\temp\20240328171935-teste.xlsx#xl/worksheets/sheet1.xml): Failed to open stream: No such file or directory in C:\xampp\htdocs\dolibarr\includes\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Security\XmlScanner.php on line 152, referer: http://localhost/

Maybe it can not find that file because it doesn't have the zip thing?


> [Thu Mar 28 13:19:38.542541 2024] [php:error] [pid 3156:tid 1900] [client ::1:59511] PHP Fatal error: Uncaught ValueError: XMLReader::XML(): Argument #1 ($source) cannot be empty in C:\xampp\htdocs\dolibarr\includes\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php:206\nStack trace:\n#0 C:\xampp\htdocs\dolibarr\includes\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php(206): XMLReader->XML('', NULL, 12)\n#1 C:\xampp\htdocs\dolibarr\core\modules\import\import_xlsx.modules.php(310): PhpOffice\PhpSpreadsheet\Reader\Xlsx->listWorksheetInfo('C:/xampp/htdocs...')\n#2 C:\xampp\htdocs\dolibarr\imports\import.php(836): ImportXlsx->import_read_record()\n#3 {main}\n thrown in C:\xampp\htdocs\dolibarr\includes\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php on line 206, referer: http://localhost/

**Comment by alihusseinc** [comment]
![aaa](https://github.com/Dolibarr/dolibarr/assets/104669840/b8950d6f-8dd3-41a4-9564-3d2076f2b64a)
This is my php.ini

**Comment by JonBendtsen** [comment]
> ![aaa](https://private-user-images.githubusercontent.com/104669840/317814019-b8950d6f-8dd3-41a4-9564-3d2076f2b64a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDU0MDIsIm5iZiI6MTcxMTY0NTEwMiwicGF0aCI6Ii8xMDQ2Njk4NDAvMzE3ODE0MDE5LWI4OTUwZDZmLThkZDMtNDFhNC05NTY0LTNkMjA3NmYyYjY0YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxNjU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGU2ZDE4YWFmYTk4MzU2NjFlNzM2ODFjM2YyNDczMTQ1ODgwNjVlNWU2ZmIzYzU0ZmVlZGZhN2RhZDEzMzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NoeqTJ8dYPr9GU4XIITEWpZWESuikaGFnxQV7jBfDtc) This is my php.ini

Yes, but is it also actually installed in your OS?

**Comment by alihusseinc** [comment]
I think that if as I would in this case??

**Comment by frederic34** [comment]
fixed here https://github.com/Dolibarr/dolibarr/pull/29011
