### ISSUE TITLE
Error when try to install develop brand

### ISSUE THREAD

**Issue by avadnc** [Dolibarr/dolibarr#30817]
### Bug

when i finish the install in dolibarr, after introducing username and password, dolibarr show this error:

`Fatal error: Uncaught TypeError: Argument 1 passed to Cronjob::create() must be an instance of User, null given, called in /Applications/XAMPP/xamppfiles/htdocs/dolidev/htdocs/core/modules/DolibarrModules.class.php on line 1692 and defined in /Applications/XAMPP/xamppfiles/htdocs/dolidev/htdocs/cron/class/cronjob.class.php:214 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/dolidev/htdocs/core/modules/DolibarrModules.class.php(1692): Cronjob->create(NULL) #1 /Applications/XAMPP/xamppfiles/htdocs/dolidev/htdocs/core/modules/DolibarrModules.class.php(563): DolibarrModules->insert_cronjobs() #2 /Applications/XAMPP/xamppfiles/htdocs/dolidev/htdocs/core/modules/modAgenda.class.php(612): DolibarrModules->_init(Array, '') #3 /Applications/XAMPP/xamppfiles/htdocs/dolidev/htdocs/core/lib/admin.lib.php(1222): modAgenda->init() #4 /Applications/XAMPP/xamppfiles/htdocs/dolidev/htdocs/install/step5.php(359): activateModule('modAgenda', 1) #5 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/dolidev/htdocs/cron/class/cronjob.class.php on line 214`

### Dolibarr Version

develop

### Environment PHP

7,4

### Environment Database

mariadb

### Steps to reproduce the behavior and expected behavior

Clean install

**Comment by mdeweerd** [comment]
Probably not related (installing with "forced" configuration) :
http://127.0.1.0/install/fileconf.php?selectlang=fr_FR

![image](https://github.com/user-attachments/assets/2a316cd0-a3c6-426f-8724-61326082c299)

**Comment by mdeweerd** [comment]
Surely related to "forced installation" as well:
![image](https://github.com/user-attachments/assets/d5d9055b-ba48-41bc-bbc6-d0ecb9024ec5)

**Comment by mdeweerd** [comment]
![image](https://github.com/user-attachments/assets/3399cc43-bb11-474e-a325-acc868b97f06)
![image](https://github.com/user-attachments/assets/c1c26ce7-f405-4501-948b-e1885afff167)

**Comment by avadnc** [comment]
Exactly, It was installed by instructing the installation process to create the database; it got to the point of creating the admin user, and that’s when the error occurred.

**Comment by cakeandmilkcup** [comment]
@avadnc @mdeweerd 
Did you find the solution?
A temporary solution:
open DolibarrModules.class.php and comment out the following lines:
```
$retCreate = $cronjob->create($user);
if ($retCreate < 0) {
      $this->error = implode("\n", array_merge([$cronjob->error], $cronjob->errors));
      return -1;
}

```

**Comment by avadnc** [comment]
Thanks
