### ISSUE TITLE
Proposal signed > Error 500, must be of type array, null given

### ISSUE THREAD

**Issue by Frankd66** [Dolibarr/dolibarr#31202]
### Bug

PHP Error 500 when trying to "Set accepted" proposal > signed > Ok > Error 500

### Dolibarr Version

20.0.0

### Environment PHP

8.2.2

### Environment Database

MariaDB 10.11.6

### Steps to reproduce the behavior and expected behavior

Just try to validate proposal by signed

### Attached files

[Fri Sep 27 17:00:48.724624 2024] [php:error] [pid 13207:tid 13207] [client 192.168.1.16:59336] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /var/www/html/dolibarr/htdocs/core/triggers/dolibarrtriggers.class.php:174
Stack trace:
#0 /var/www/html/dolibarr/htdocs/core/triggers/dolibarrtriggers.class.php(174): array_merge()
#1 /var/www/html/dolibarr/htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php(95): DolibarrTriggers->setErrorsFromObject()
#2 /var/www/html/dolibarr/htdocs/core/class/interfaces.class.php(193): InterfaceWorkflowManager->runTrigger()
#3 /var/www/html/dolibarr/htdocs/core/class/commonobject.class.php(6112): Interfaces->run_triggers()
#4 /var/www/html/dolibarr/htdocs/comm/propal/class/propal.class.php(2612): CommonObject->call_trigger()
#5 /var/www/html/dolibarr/htdocs/comm/propal/card.php(748): Propal->closeProposal()
#6 {main}
  thrown in /var/www/html/dolibarr/htdocs/core/triggers/dolibarrtriggers.class.php on line 174, referer: http://192.168.1.41/dolibarr/htdocs/comm/propal/card.php?id=1931&action=closeas&token=a29c80b2900d0793f4d93f17f8e7f96b```

**Comment by Frankd66** [comment]
Solved. TOS external module make this if default value is not filled
