### ISSUE TITLE
Error while generating delivery note PDF file (upgraded to v20.0.0)

### ISSUE THREAD

**Issue by iactiva** [Dolibarr/dolibarr#31249]
### Bug

After upgrading to V20.0.0 I'm getting error every time I try to generate a delivery note expedition. It seems to fail when creating the pdf file.

From an order > create expedition > validate > blank screen
Expedition is created but there is no pdf file. Also pressing generate button fails again.

PHP error below.

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getIdContact() on null in core/modules/expedition/doc/pdf_albaran.modules.php:1077\nStack trace:\n#0 core/modules/expedition/doc/pdf_albaran.modules.php(346): pdf_albaran->_pagehead()\n#1 core/class/commonobject.class.php(5818): pdf_albaran->write_file()\n#2 expedition/class/expedition.class.php(2622): CommonObject->commonGenerateDocument()\n#3 core/actions_builddoc.inc.php(97): Expedition->generateDocument()\n#4 expedition/card.php(159): include('...')\n#5 {main}\n  thrown in core/modules/expedition/doc/pdf_albaran.modules.php on line 1077', referer: https://dolibarr-test.local/expedition/card.php?id=194&save_lastsearch_values=1

### Dolibarr Version

20.0.0

### Environment PHP

8.1

### Environment Database

MariaDB 10.6

### Steps to reproduce the behavior and expected behavior

From an order > create expedition > validate > blank screen
Expedition is created but there is no pdf file. Also pressing generate button fails again.

**Comment by iactiva** [comment]
The problem come from using an old template file. Using default template 'espadon' works.
