### ISSUE TITLE
Timezone Error?

### ISSUE THREAD

**Issue by stan-thomas** [Dolibarr/dolibarr#32458]
### Bug

This is from the apache error log 

PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone (Asia/Calcutta) in /usr/share/dolibarr/htdocs/core/lib/functions.lib.php:2852\nStack trace:\n#0 /usr/share/dolibarr/htdocs/core/lib/functions.lib.php(2852): DateTimeZone->__construct()\n#1 /usr/share/dolibarr/htdocs/main.inc.php(2454): dol_print_date()\n#2 /usr/share/dolibarr/htdocs/main.inc.php(2343): top_menu_user()\n#3 /usr/share/dolibarr/htdocs/main.inc.php(1545): top_menu()\n#4 /usr/share/dolibarr/htdocs/index.php(87): llxHeader()\n#5 {main}\n  thrown in /usr/share/dolibarr/htdocs/core/lib/functions.lib.php on line 2852

### Dolibarr Version

19.0.4

### Environment PHP

8.1 and 8.2

### Environment Database

Postgres 17

### Steps to reproduce the behavior and expected behavior

Happens immediately after login. I upgraded my server. I guess the PHP version has changed. Can't be sure. I'm getting this error in both 8.1 and 8.2 PHP.

**Comment by denischupau** [comment]
Hi, maybe it is related to this bug? #32920 

Something changed in the handling of Date/Time exceptions in from PHP 8.2 to PHP 8.3:
From the PHP documentation DateTimeZone::__construct() : "This method throws DateInvalidTimeZoneException if the timezone supplied is not recognised… Prior to PHP 8.3, this was an Exception instead."

**Comment by pixodeo** [comment]
Looks already handled in current versions. dol_print_date() on 21.0+ wraps `new DateTimeZone($offsettzstring)` in a try/catch with fallback to UTC (htdocs/core/lib/functions.lib.php:3903-3910), so an Asia/Calcutta legacy alias dropped by tzdata only triggers a syslog warning, not a fatal. Could you retest on 23.0 and close if green? On 19.0.4 you can either update MAIN_DOLIBARR_USER_TIMEZONE to Asia/Kolkata or upgrade Dolibarr.
