### ISSUE TITLE
Fatal Error: Can't Login on 7.0.3

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#9234]
# Bug
Upgraded to 7.0.3 and used it all day.  Then randomly in the evening i wasn't allowed to login form a different browser.  Got a blank page instead of the login screen.  Tried to reinstall and still have the same problem.  Will re-upload all files now and try again.

The webhost company said they found the below error in the server log which is dolibarr-specific so they cant help me.

## Environment
- **Version**: 7.0.3
- **OS**: CentOS7
- **Web server**: Linux VPS
- **PHP**: 7
- **Database**: MySQL
- **URL(s)**: 

`[13-Aug-2018 08:42:11 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function getCommonSubstitutionArray() in /home/pewsedofitsc/public_html/dolibarr/core/lib/security2.lib.php:276`
`Stack trace:`
`#0 /home/pewsedofitsc/public_html/dolibarr/main.inc.php(569): dol_loginfunction(Object(Translate), Object(Conf), Object(Societe))`
`#1 /home/pewsedofitsc/public_html/dolibarr/index.php(29): require('/home/pewsedofi...')`
`#2 {main}
  thrown in /home/pewsedofitsc/public_html/dolibarr/core/lib/security2.lib.php on line 276`

**Comment by aljawaid** [comment]
Re-uploading the ftp files and starting the installer again seemed to have solved the issue and given me access again.
